

List<String> getLyrics() {

  return ['Pobre de quien viva sin dudas',
  'mi mundo a oscuras y yo pagando las facturas',
  'el alcohol mata lo que el olvido cura',
  'días duros hacen gente dura',
  'metiendole un pañuelo por el coño a mi musa',
  'a ver si sigue siendo pura',
  'me enamoró la vida por puta',
  'esta cruzándome los dedos a la vez que jura',
  'loco yo no se que sera de mi',
  'ni lo que nos queda por vivir',
  'no aprende mi cabeza, no aprende mi cabeza',
  'la muerte se llevo a mi padre y aun me río de ella',
  'no puedo yo estar cuerdo',
  'a la primera copa ya te olvido y a la quinta te recuerdo',
  'no jures por tus muertos, jura por tus vivos',
  'que dos veces no se muere o no estarás muy convencido',
  'están comprando sueños con dinero que no vale',
  'en el mundo de los precios el mas caro es quien no tiene',
  'en el planeta el pánico',
  'la ignorancia tiene mas rehenes que el estado islámico',
  'labios que se fueron nunca vuelven',
  'y si lo hacen no serán los mismos que recuerden',
  'muerden los perros que tienen hambre',
  'a sangre solo lo alimentan con mas sangre',
  '',
  'Esta no es mi cama y madre tengo frío',
  'porque si no estas en casa siempre me olvido el abrigo',
  'me llama y me pregunta si he comido',
  'a ver como le explico que he perdido ya 10 kilos',
  'Esta no es mi cama y madre tengo frío',
  'porque si no estas en casa siempre me olvido el abrigo',
  'me llama y me pregunta si he comido',
  'a ver como le explico que he perdido ya 10 kilos',
  '',
  'Loco por volver, por volver a ver, por volver a verte',
  'me dicen tienes curro tienes suerte',
  'no estoy viviendo estoy renderizando el alma',
  'cuando la soledad es rutina el bullicio es calma',
  'en una cocina inglesa 10 polacos gritan Kurwa',
  'yo acordándome de Emilio Rato y sus cuentas en Suiza',
  'esa es la pregunta',
  'cuantas puta hay pa que haya en el mundo tanto hijo de puta',
  'seremos infelices con el tiempo',
  'la suerte del ignorante siempre estar contento',
  'avante, avante, que alante esta el templo',
  'donde las abuelas piden salud pa sus nietos',
  'mama perdona por estar tan loco',
  'no soy un buen ejemplo pero malo tampoco',
  'añoro el micro el calor de los focos',
  'que rapers hay muchos pero reales muy pocos',
  'sin dinero en nuestros videos no seria real',
  'si tengo la cuenta del banco embargá',
  'ojeras de salir y empalmar pa trabajar',
  'la suela de los botines gasta',
  'cuando pones la alarma y te dice que en 4 horas ya',
  'te tienes que levantar',
  'no me vengas a hablar del barrio vendiéndome ruina',
  'que el barrio es pa currantes y tu no has currado en tu vida',
  '',
  'Esta no es mi cama y madre tengo frío',
  'porque si no estas en casa siempre me olvido el abrigo',
  'me llama y me pregunta si he comido',
  'a ver como le explico que he perdido ya 10 kilos',
  'Esta no es mi cama y madre tengo frío',
  'porque si no estas en casa siempre me olvido el abrigo',
  'me llama y me pregunta si he comido',
  'a ver como le explico que he perdido ya 10 kilos'];

}